
services:
  app:
    image: customer-management-docker
    build: .
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - mysql-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/customer_management?allowPublicKeyRetrieval=True&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql-service:
    container_name: mysql-service
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: customer_management
      MYSQL_ROOT_PASSWORD: root